---
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing Sceptre
      - pip install -r $CODEBUILD_SRC_DIR/requirements.txt
  build:
    commands:
      - echo Started build for last commit $CODEBUILD_SOURCE_VERSION
      - git log -1 HEAD --raw
      - echo Updating stacks
      - sceptre launch -y prod
    finally:
      - echo Stacks got updated successfully
