template_path: subnets.yaml

parameters:
  VPCStackName: !stack_output {{ env }}/vpc.yaml::VPC
  PubCidrBlockA: 10.128.16.0/24
  PubCidrBlockB: 10.128.17.0/24
  PubCidrBlockC: 10.128.18.0/24
  PrivCidrBlockA: 10.128.20.0/22
  PrivCidrBlockB: 10.128.24.0/22
  PrivCidrBlockC: 10.128.28.0/22
#  StackName: network..
#  Environment: {{ env }}
