---
AWSTemplateFormatVersion: "2010-09-09"
Description: "VPC Provisioning"
Parameters:
  CidrBlock:
    Type: String
    Description: A VPC CIDR Block
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  StackName:
    Type: String
  Environment:
    Type: String
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Ref StackName
        - Key: Environment
          Value: !Ref Environment
Outputs:
  VPC:
    Value: !Ref VPC

